import { StyleSheet } from 'react-native';
import { Theme } from '../../constants/Theme';
import { createGlassCard, screenHeaderRow } from './sharedStyles';

export const intakeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Theme.colors.background,
    },
    scroll: {
        flex: 1,
    },
    header: screenHeaderRow,
    headerPersona: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: Theme.spacing.sm,
    },
    headerTitle: {
        color: Theme.colors.white,
        fontSize: 17,
        fontWeight: Theme.typography.weights.primary,
        opacity: 0.9,
        flexShrink: 1,
        letterSpacing: -0.3,
    },
    headerAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: Theme.colors.glassBorder,
        backgroundColor: Theme.colors.glass,
    },
    headerAvatarPlaceholder: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: Theme.colors.glassBorder,
        backgroundColor: Theme.colors.glassSubtle,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerAvatarText: {
        color: Theme.colors.textMuted,
        fontSize: 12,
        fontWeight: Theme.typography.weights.primary,
    },
    headerRightSpacer: {
        width: 32,
        height: 32,
    },
    content: {
        paddingHorizontal: Theme.spacing.lg,
        paddingBottom: Theme.spacing.xxl,
        alignItems: 'center',
        paddingTop: Theme.spacing.md,
    },
    personaContainer: {
        alignItems: 'center',
        marginBottom: 40,
    },
    avatarPlaceholder: createGlassCard(
        {
            width: 130,
            height: 130,
            backgroundColor: Theme.colors.glass,
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: Theme.spacing.md,
        },
        { borderRadius: 65, clip: false }
    ),
    avatarImage: {
        width: 130,
        height: 130,
        borderRadius: 65,
        marginBottom: Theme.spacing.md,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
    },
    avatarText: {
        color: Theme.colors.white,
        fontSize: 52,
        fontWeight: Theme.typography.weights.black,
    },
    statusText: {
        color: Theme.colors.primary,
        fontSize: 16,
        fontWeight: Theme.typography.weights.primary,
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    instruction: {
        color: Theme.colors.textMuted,
        textAlign: 'center',
        fontSize: 16,
        marginTop: 40,
        lineHeight: 26,
        fontWeight: Theme.typography.weights.secondary,
    },
    micHint: {
        color: Theme.colors.textMuted,
        textAlign: 'center',
        fontSize: 14,
        lineHeight: 20,
        fontWeight: Theme.typography.weights.secondary,
        marginTop: -12,
    },
    voiceError: {
        color: Theme.colors.error,
        textAlign: 'center',
        fontSize: 13,
        lineHeight: 18,
        fontWeight: Theme.typography.weights.primary,
        marginTop: 10,
    },
    card: createGlassCard(
        {
            width: '100%',
            backgroundColor: Theme.colors.glass,
            padding: Theme.spacing.md,
            marginTop: Theme.spacing.sm,
        },
        { withShadow: false }
    ),
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: Theme.spacing.md,
    },
    cardTitle: {
        color: Theme.colors.white,
        fontSize: 16,
        fontWeight: Theme.typography.weights.primary,
    },
    cardTextMuted: {
        color: Theme.colors.textMuted,
        fontSize: 14,
        lineHeight: 22,
        marginTop: Theme.spacing.md,
        fontWeight: Theme.typography.weights.secondary,
    },
    secondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
        height: 44,
        borderRadius: 22,
        backgroundColor: Theme.colors.surface,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
    },
    secondaryButtonText: {
        color: Theme.colors.white,
        fontSize: 14,
        fontWeight: Theme.typography.weights.primary,
    },
    moodCarouselContent: {
        paddingRight: Theme.spacing.sm,
        gap: 12,
    },
    moodOption: {
        width: 128,
        height: 88,
        borderRadius: 18,
        overflow: 'hidden',
        backgroundColor: Theme.colors.surface,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
    },
    moodOptionPick: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingHorizontal: Theme.spacing.sm,
    },
    moodOptionPickText: {
        color: Theme.colors.white,
        fontSize: 12,
        fontWeight: Theme.typography.weights.primary,
    },
    moodOptionImage: {
        width: '100%',
        height: '100%',
    },
    moodOptionOverlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: Theme.colors.scrim,
    },
    moodOptionTheme: {
        color: Theme.colors.white,
        fontSize: 11,
        fontWeight: Theme.typography.weights.primary,
        letterSpacing: 0.5,
    },
    moodOptionSelected: {
        borderColor: Theme.colors.primary,
    },
    moodOptionDisabled: {
        opacity: 0.3,
    },
    soundscapeHeader: {
        marginBottom: Theme.spacing.sm,
    },
    soundscapeSelect: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        width: '100%',
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 18,
        backgroundColor: Theme.colors.surface,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
    },
    soundscapeSelectText: {
        flex: 1,
        color: Theme.colors.primary,
        fontSize: 12,
        fontWeight: Theme.typography.weights.primary,
        letterSpacing: 0.3,
    },
    soundscapeSelectTextOff: {
        color: Theme.colors.textMuted,
    },
    soundscapeDropdown: {
        marginTop: Theme.spacing.md,
        gap: 10,
    },
    soundscapeOptionRow: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 18,
        backgroundColor: Theme.colors.surface,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
    },
    soundscapeOptionRowActive: {
        backgroundColor: Theme.colors.primarySoft,
        borderColor: Theme.colors.primary,
    },
    soundscapeOptionText: {
        color: Theme.colors.white,
        fontSize: 13,
        fontWeight: Theme.typography.weights.primary,
    },
    soundscapeOptionTextActive: {
        color: Theme.colors.primary,
    },
    pickedImage: {
        width: '100%',
        height: 180,
        marginTop: Theme.spacing.md,
        borderRadius: 18,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
    },
    analysisContainer: {
        marginTop: Theme.spacing.md,
    },
    analysisRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    analysisLabel: {
        color: Theme.colors.primary,
        fontSize: 12,
        fontWeight: Theme.typography.weights.black,
        letterSpacing: 1,
        textTransform: 'uppercase',
        marginBottom: Theme.spacing.sm,
    },
    analysisText: {
        color: Theme.colors.text,
        fontSize: 14,
        lineHeight: 22,
        fontWeight: Theme.typography.weights.primary,
    },
    analysisTextMuted: {
        color: Theme.colors.textMuted,
        fontSize: 14,
        fontWeight: Theme.typography.weights.semibold,
    },
    analysisTextError: {
        color: Theme.colors.error,
        fontSize: 14,
        lineHeight: 22,
        fontWeight: Theme.typography.weights.semibold,
    },
    retryRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginTop: Theme.spacing.md,
    },
    retryText: {
        color: Theme.colors.primary,
        fontSize: 14,
        fontWeight: Theme.typography.weights.extraBold,
    },
    footer: {
        padding: Theme.spacing.xl,
        alignItems: 'center',
        gap: 24,
    },
    actionButton: {
        width: '100%',
        height: 60,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        ...Theme.shadow,
    },
    generateButton: {
        backgroundColor: Theme.colors.white,
    },
    generateButtonText: {
        color: Theme.colors.black,
        fontSize: 18,
        fontWeight: Theme.typography.weights.black,
    },
    micButton: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: Theme.colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
        ...Theme.shadow,
    },
    micButtonWrapper: {
        width: 112,
        height: 112,
        alignItems: 'center',
        justifyContent: 'center',
    },
    micGlow: {
        ...StyleSheet.absoluteFillObject,
        alignItems: 'center',
        justifyContent: 'center',
    },
    disabledButton: {
        opacity: 0.3,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        padding: Theme.spacing.xl,
        backgroundColor: Theme.colors.scrim,
    },
    overlayCard: {
        width: '100%',
        borderRadius: Theme.glass.borderRadius,
        padding: Theme.spacing.xl,
        alignItems: 'center',
        gap: Theme.spacing.md,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
        overflow: 'hidden',
    },
    overlayArtwork: {
        width: 220,
        height: 220,
        borderRadius: Theme.glass.borderRadius,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
        opacity: 0.9,
    },
    overlayTitle: {
        color: Theme.colors.white,
        fontSize: 18,
        fontWeight: Theme.typography.weights.black,
        textAlign: 'center',
    },
    overlayProgressPill: {
        width: '100%',
        paddingVertical: Theme.spacing.sm,
        paddingHorizontal: Theme.spacing.md,
        borderRadius: Theme.glass.borderRadius,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
        backgroundColor: Theme.colors.glassSubtle,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
    },
    overlayProgressText: {
        color: Theme.colors.white,
        fontSize: 14,
        fontWeight: Theme.typography.weights.extraBold,
        letterSpacing: 0.2,
    },
    overlayProgressShimmer: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: -120,
        width: 120,
        opacity: 0.35,
    },
    overlayProgressTrack: {
        width: '100%',
        height: 10,
        borderRadius: 6,
        flexDirection: 'row',
        backgroundColor: Theme.colors.glassSubtle,
        borderWidth: Theme.glass.borderWidth,
        borderColor: Theme.colors.glassBorder,
        overflow: 'hidden',
    },
    overlayProgressFill: {
        height: '100%',
        borderRadius: 6,
        backgroundColor: Theme.colors.primary,
        opacity: 0.75,
    },
});
